content:

  - name: events
    label: Eventi
    path: events
    filename: '{year}-{month}-{day}-{fields.title}.md'
    type: collection
    create: true
    view:
      fields: [date, title, venue]
    fields:
      - name: date
        label: Data
        type: date
        options:
          time: false
          format: "yyyy-MM-dd"

      - name: title
        label: Titolo
        type: string

      - name: venue
        label: Luogo
        type: string

      - name: performers
        label: Esecutori
        type: text

      - name: url
        label: Link info / biglietti
        type: string


  - name: absolute
    label: Musica Assoluta
    path: absolute
    filename: '{fields.name}.md'
    type: collection
    create: true
    view:
      fields: [name, instrumentation, premiere_date]
    fields:
      - name: name
        label: Nome composizione
        type: string

      - name: instrumentation
        label: Organico
        type: text

      - name: composition_type
        label: Tipo di composizione
        type: select
        options:
          values:
            - Symphonic
            - Chamber
            - Theatre
            - Movie
        default: Symphonic
          
      - name: premiere_date
        label: Data prima esecuzione
        type: date
        options:
          time: false
          format: "yyyy-MM-dd"

      - name: url
        label: Link Youtube/Spotify
        type: text


  - name: news
    label: Notizie
    path: news
    filename: '{year}-{month}-{day}-{fields.title}.md'
    type: collection
    create: true
    view:
      fields: [date, title]
    fields:
      - name: date
        label: Data
        type: date
        options:
          time: false
          format: "yyyy-MM-dd"

      - name: title
        label: Titolo
        type: string

      - name: subtitle
        label: Sottotitolo
        type: string

      - name: url
        label: URL notizia
        type: string

      - name: cover
        label: Immagine di copertina
        type: image

      - name: size
        label: Dimensione card
        type: select
        options:
          values:
            - small
            - medium
            - large
        default: medium

  - name: filmography
    label: Filmografia
    path: filmography
    filename: '{fields.title}.md'
    type: collection
    create: true
    view:
      fields: [title, director, date]
    fields:
      - name: title
        label: Titolo
        type: string

      - name: director
        label: Regista
        type: string

      - name: date
        label: Data di uscita
        type: date
        options:
          time: false
          format: "yyyy-MM-dd"

      - name: poster
        label: Poster / Immagine
        type: image

      - name: synopsis
        label: Sinossi
        type: rich-text

      - name: trailer_url
        label: Link trailer YouTube
        type: string

      - name: spotify_key
        label: Key / Link Spotify
        type: string

  - name: biography
    label: Biografia
    path: biography
    filename: 'biography.md'
    type: file
    fields:
      - name: title1
        label: Titolo 1
        type: text

      - name: subtitle1
        label: Paragrafo 1 (inserire <br> per andare a capo)
        type: text

      - name: img1
        label: Immagine 1
        type: image

      - name: title2
        label: Titolo 2
        type: text

      - name: subtitle2
        label: Paragrafo 2 (inserire <br> per andare a capo)
        type: text

      - name: img2
        label: Immagine2 
        type: image


media:
  input: assets/news
  output: /assets/news