content:

  - name: events
    label: Eventi
    path: events
    filename: '{year}-{month}-{day}-{fields.title}.md'
    type: collection
    create: true
    view:
      fields: [date, title, venue]
    fields:
      - name: date
        label: Data
        type: date
        options:
          time: false
          format: "yyyy-MM-dd"

      - name: title
        label: Titolo
        type: string

      - name: venue
        label: Luogo
        type: string

      - name: performers
        label: Esecutori
        type: text

      - name: url
        label: Link info / biglietti
        type: string


  - name: repertoire
    label: Repertorio
    path: repertoire
    filename: '{fields.name}.md'
    type: collection
    create: true
    view:
      fields: [name, instrumentation, premiere_date]
    fields:
      - name: name
        label: Nome composizione
        type: string

      - name: instrumentation
        label: Organico
        type: text

      - name: composition_type
        label: Tipo di composizione
        type: string

      - name: premiere_date
        label: Data prima esecuzione
        type: date
        options:
          time: false
          format: "yyyy-MM-dd"


  - name: news
    label: Notizie
    path: news
    filename: '{year}-{month}-{day}-{fields.title}.md'
    type: collection
    create: true
    view:
      fields: [date, title]
    fields:
      - name: date
        label: Data
        type: date
        options:
          time: false
          format: "yyyy-MM-dd"

      - name: title
        label: Titolo
        type: string

      - name: subtitle
        label: Sottotitolo
        type: string

      - name: url
        label: URL notizia
        type: string

      - name: cover
        label: Immagine di copertina
        type: image

      - name: size
        label: Dimensione card
        type: select
        options:
          values:
            - small
            - medium
            - large
        default: medium


media:
  input: assets/news
  output: /assets/news